export const ITEM_CREATE = 'ITEM_CREATE'
export const ITEM_REQUEST_ALL = 'ITEM_REQUEST_ALL'
export const ITEM_UPDATE = 'ITEM_UPDATE'
export const ITEM_DELETE = 'ITEM_DELETE'
export const ITEM_REQUEST_SEARCH = 'ITEM_REQUEST_SEARCH'

export const CREATE_ORDER = 'CREATE_ORDER'